openshiftpods: fix TypeError exception in cleanup
The error was:

    ERROR nodepool.driver.openshiftpods.OpenshiftPodsProvider: Couldn't remove pod zuul-ansible-roles-0000000033
    Traceback (most recent call last):
      File "zuul/lib/python3.9/site-packages/nodepool/driver/openshiftpods/provider.py", line 105, in cleanupNode
        self.k8s_client.delete_namespaced_pod(
    TypeError: delete_namespaced_pod() takes 3 positional arguments but 4 were given

Since kubernetes 9.0.0 (cd411d27071797c0bad90b158a3ba335ee6f3b56)
delete_namespaced_pod method signature has been updated:

    -    def delete_namespaced_pod(self, name, namespace, body, **kwargs):
    +    def delete_namespaced_pod(self, name, namespace, **kwargs):

body and kwargs parameters were/are passed to another method.

This change allows to handle both versions.

Change-Id: I54cea6984572eec4559a029a0d57b85df2283352