Add debug info on json parse error of image upload
We encountered a broken upload entry which is lead to an exception in
the cleanup worker and querying the image-list [1]. Add more debug
info so we can determine the broken upload entry in zk.

[1] Trace:
2020-04-01 12:05:05,380 ERROR nodepool.builder.CleanupWorker.0: Exception in CleanupWorker:
Traceback (most recent call last):
  File "/opt/nodepool/lib/python3.6/site-packages/nodepool/builder.py", line 557, in run
    self._run()
  File "/opt/nodepool/lib/python3.6/site-packages/nodepool/builder.py", line 582, in _run
    self._cleanup()
  File "/opt/nodepool/lib/python3.6/site-packages/nodepool/builder.py", line 379, in _cleanup
    self._buildUploadRecencyTable()
  File "/opt/nodepool/lib/python3.6/site-packages/nodepool/builder.py", line 194, in _buildUploadRecencyTable
    2, image, build.id, provider, zk.READY)
  File "/opt/nodepool/lib/python3.6/site-packages/nodepool/zk.py", line 1404, in getMostRecentBuildImageUploads
    uploads = self.getUploads(image, build_number, provider, states)
  File "/opt/nodepool/lib/python3.6/site-packages/nodepool/zk.py", line 1373, in getUploads
    data = self.getImageUpload(image, build_number, provider, upload)
  File "/opt/nodepool/lib/python3.6/site-packages/nodepool/zk.py", line 1337, in getImageUpload
    d = ImageUpload.fromDict(self._bytesToDict(data),
  File "/opt/nodepool/lib/python3.6/site-packages/nodepool/zk.py", line 810, in _bytesToDict
    return json.loads(data.decode('utf8'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Change-Id: Ic0f0233edfb87204cca68ae8a36416e13d05b311