Fix typo that crashes playback worker when under load
When reaching the warning level of the playback worker it crashes with
an exception [1]. The reason is a typo in the variable initialization.

[1] Trace
Exception in thread Thread-6 (_playbackWorker):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/nodepool/lib/python3.10/site-packages/nodepool/zk/zookeeper.py", line 926, in _playbackWorker
    if now - self._last_playback_warning > 60:
AttributeError: 'NodeCache' object has no attribute '_last_playback_warning'. Did you mean: '_last_playblack_warning'?

Change-Id: Ib52d475edaebb960f2350cca0f61df779539873f