Ignore removed provider in _cleanupLeakedInstances
Sometimes when a provider is removed _cleanupLeakedInstances fails
with [1] because the provider has been removed between config
iteration and getting the manager. This can be safely ignored.

[1] Traceback
ERROR:nodepool.CleanupWorker:Exception in CleanupWorker (leaked instance cleanup)
Traceback (most recent call last):
  File "/Users/q282539/repos/cc/nodepool/nodepool/launcher.py", line 598, in _run
    task()
  File "/Users/q282539/repos/cc/nodepool/nodepool/launcher.py", line 473, in _cleanupLeakedInstances
    manager = self._nodepool.getProviderManager(provider.name)
  File "/Users/q282539/repos/cc/nodepool/nodepool/launcher.py", line 792, in getProviderManager
    return self.config.provider_managers[provider_name]
KeyError: 'fake-provider2'

Change-Id: Iae1266efc6e17b50b5a176afc5b28f26f2fa7177