Copy cached objects in tree cache before iterating
Before iterating over the cached objects of the tree cache we need to
create a shallow copy of the dictionary to avoid runtime errors when the
dict is modified.

  File "/opt/nodepool/lib/python3.10/site-packages/nodepool/driver/statemachine.py", line 119, in startStateMachine
    cloud_image = self.zk.getMostRecentImageUpload(
  File "/opt/nodepool/lib/python3.10/site-packages/nodepool/zk/zookeeper.py", line 1989, in getMostRecentImageUpload
    uploads = self.getCachedImageUploads()
  File "/opt/nodepool/lib/python3.10/site-packages/nodepool/zk/zookeeper.py", line 2029, in getCachedImageUploads
    return self._image_cache.getUploads()
  File "/opt/nodepool/lib/python3.10/site-packages/nodepool/zk/zookeeper.py", line 1124, in getUploads
    items = sorted(items, key=lambda x: x[0])
RuntimeError: dictionary changed size during iteration

Change-Id: I59eccb1bcc6f0e2313261a61f9e4ebe19bb11e4e