Double check node request during node cleanup
This change fixes a race condition between a node getting re-used and
the cleanup of reusable ready nodes.

The sequence of events seems to be the following:
* "ready" node-x allocated to request-1 with request-1 no longer
  existing
* cleanup-worker-1 starts iterating (cached data)
* another cleanup-worker-2 starts iterating (cached data)
* node-x is deallocated by a cleanup-worker-1
* node-x is allocated to request-2
* cleanup-worker-2 deallocates node-x as it is operating on cached data
  thinking that the node is still allocated to request-1
* node-x is allocated to request-3
* executor for job-2 tries to lock node-x (previously assigned to
  request-3) leading to the following exception

2023-05-24 11:55:12,116 ERROR zuul.nodepool: [e: 0943d670-fa28-11ed-8540-a307d01e6b77] Error locking nodes:
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.10/site-packages/zuul/nodepool.py", line 381, in lockNodes
    raise Exception("Node %s allocated to %s, not %s" %
Exception: Node 0032857715 allocated to 100-0031415561, not 200-0031415229

Change-Id: If80624cad9a7beb13b6ece3dadddb5beba9243fc