Make config more tolerant of errors
Currently, when the config contains no definition for elements-dir
or script-dir, there will be a pretty obscure error like

TypeError: execve() arg 3 contains a non-string value

So use an empty string as default for these variables instead of None.

Change-Id: Id683a57b15dcb0974c9a58070e971f7ea0dc9b99