openstack: decline request for labels un-available in current pool
When a provider is configured with multiple pool with different labels
list, then we need to decline the request for unavailable labels,
otherwise the service loop with this exception:

INFO nodepool.PoolWorker.default: Assigning node request <NodeRequest {'node_types': ['dib-centos-7'], ...}
ERROR nodepool.driver.NodeRequestHandler[XXX-PoolWorker.default]: Declining node request 200-0000087147 due to exception in NodeRequestHandler:
Traceback (most recent call last):
  File "nodepool/driver/__init__.py", line 628, in run
    self._runHandler()
  File "nodepool/driver/__init__.py", line 515, in _runHandler
    elif not self.imagesAvailable():
  File "nodepool/driver/openstack/handler.py", line 278, in imagesAvailable
    if self.pool.labels[label].cloud_image:
KeyError: 'dib-centos-7'

Change-Id: I1c52db4d89b51657fc9f1d5e3b21646427619d2c