Use CWD as default for directory variables
Currently, when the config contains no definition for elements-dir
or script-dir, there will be a pretty obscure error like

TypeError: execve() arg 3 contains a non-string value

when disk-image-builder is executed. So use '.' as default for these
variables instead of None.

Change-Id: Id683a57b15dcb0974c9a58070e971f7ea0dc9b99