Update patch set 1
Patch Set 1: Code-Review+2 Workflow+1

This broke production with this 

2015-11-15 18:44:51,096 ERROR nodepool.NodeLauncher: HTTPError launching node id: 5868403 in provider: hpcloud-b3 error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nodepool/nodepool.py", line 406, in _run
    dt = self.launchNode(session)
  File "/usr/local/lib/python2.7/dist-packages/nodepool/nodepool.py", line 543, in launchNode
  File "/usr/local/lib/python2.7/dist-packages/nodepool/nodepool.py", line 564, in createJenkinsNode
    jenkins.createNode(**args)
  File "/usr/local/lib/python2.7/dist-packages/nodepool/jenkins_manager.py", line 112, in createNode
    return self.submitTask(CreateNodeTask(**args))
  File "/usr/local/lib/python2.7/dist-packages/nodepool/task_manager.py", line 119, in submitTask
    return task.wait()
  File "/usr/local/lib/python2.7/dist-packages/nodepool/task_manager.py", line 57, in run
    self.done(self.main(client))
  File "/usr/local/lib/python2.7/dist-packages/nodepool/jenkins_manager.py", line 49, in main
    jenkins.create_node(**args)
  File "/usr/local/lib/python2.7/dist-packages/jenkins/__init__.py", line 1165, in create_node
    self._build_url(CREATE_NODE, params), b''))
  File "/usr/local/lib/python2.7/dist-packages/jenkins/__init__.py", line 341, in jenkins_open
    response = urlopen(req, timeout=self.timeout).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 400: Bad Request

Patch-set: 1
Reviewer: Gerrit User 2 <2@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Workflow=+1