Exclude openstacksdk 2.0.0
This version includes a partial implementation of a migration to Proxy
objects for block limitations. Unfortunately that implemenation only
covered cinder v3 apis and not cinder v2 apis. In the case of cinder v2
apis it just breaks on us:

  2023-10-31 16:37:06,135 ERROR nodepool.PoolWorker.rax-iad-main: Error in PoolWorker:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.11/site-packages/nodepool/launcher.py", line 491, in run
      for chunk in self._assignHandlers():
    File "/usr/local/lib/python3.11/site-packages/nodepool/launcher.py", line 242, in _assignHandlers
      reasons_to_decline = rh.getDeclinedReasons()
                           ^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/nodepool/driver/__init__.py", line 600, in getDeclinedReasons
      elif not self.hasProviderQuota(self.request.node_types):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/nodepool/driver/statemachine.py", line 520, in hasProviderQuota
      cloud_quota = self.manager.estimatedNodepoolQuota()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/nodepool/driver/utils.py", line 312, in estimatedNodepoolQuota
      nodepool_quota = self.getProviderLimits()
                       ^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/nodepool/driver/statemachine.py", line 785, in getProviderLimits
      return self.adapter.getQuotaLimits()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/nodepool/driver/openstack/adapter.py", line 500, in getQuotaLimits
      volume = self._client.get_volume_limits()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/openstack/cloud/_block_storage.py", line 277, in get_volume_limits
      return self.block_storage.get_limits(**params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: 'Proxy' object has no attribute 'get_limits'

We can exclude the broken version for now.

Change-Id: Ib3bac4c47db01a1c5025c07173053495fc493ce9