Fix race condition with node reuse and multiple providers
While running multiple nodepool replicas on the same provider we faced
a race condition that lead to inconsistent nodes and an error during
locking nodes in zuul [1].

Upon log anlysis this is the sequence that lead to the issue:
- provider 1 gets 200-0030735612
- provider 1 creates node 0032198309, attaches it to the node request and unlocks it
- provider 2 re-uses the node for 100-0030736038 because it can lock the node but didn't
  have the updated node yet which means it's not allocated to a node request
- zuul tries to lock the node and faces [1].

This can be solved by checking if the node is still unallocated after
locking to make sure the node didn't change under us before locking.

[1] Zuul exception
023-05-16 11:36:16,292 ERROR zuul.nodepool: [e: b1dcc890-f3da-11ed-852e-3c4f498e591d] Error locking nodes:
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.10/site-packages/zuul/nodepool.py", line 429, in acceptNodes
    nodes = self.lockNodes(request, nodeset)
  File "/opt/zuul/lib/python3.10/site-packages/zuul/nodepool.py", line 381, in lockNodes
    raise Exception("Node %s allocated to %s, not %s" %
Exception: Node 0032198309 allocated to 100-0030736038, not 200-0030735612

Change-Id: I774616a0481721e27e6b0db5168d3a248ba0b818