Update patch set 1
Patch Set 1:

recheck because, strangely...

Theme error:
An error happened in rendering the page aws.
Reason: ValueError('too many values to unpack (expected 3)')
ERROR: InvocationError for command /home/zuul/src/opendev.org/zuul/nodepool/.tox/docs/bin/sphinx-build -E -W -d doc/build/doctrees -b html doc/source/ doc/build/html (exited with code 2)

If that's persistent, I can't imagine how it managed to merge.

Patch-set: 1