Rework error messages for leaked nodes
One of the OpenDev launchers is currently being flooded with

 2023-01-17 22:49:21,384 ERROR nodepool.StateMachineProvider.linaro-us-regionone: Couldn't consider invalid node ...
 Traceback (most recent call last):
   File "/usr/local/lib/python3.11/site-packages/nodepool/driver/utils.py", line 373, in estimatedNodepoolQuotaUsed
     if node.type[0] not in provider_pool.labels:
        ~~~~~~~~~^^^
 IndexError: list index out of range

This has happened after the recent merge of the statemachine driver
(Ie59a4e9f09990622b192ad840d9c948db717cce2).

Prior to this refactoring, the openstack driver would create a "dummy"
ZK node for leaked instances to try and have nodepool delete them.
These dummy nodes would not have a type as they may not actually
correspond to any label currently configured.

These should have been deleted in a timely fashion, but due to what
appears to be some stuck nodes in an upstream provider, the OpenDev ZK
still has a bunch of these old "dummy" nodes.

A prior version of this change prevented this error by looking up
these leaked nodes by flavor directly recording resource information
in the dummy-node.  This seems unnecessary now and would require
adding more to the statemachine abstractions.

However, I think the error case and messages can be improved here.
This detects the missing type, and tries to give some more detail
error output.

Change-Id: I4a6e5af83fe4e0db2b17b0ec9b5a47f1aa10bf32